# language: python
# sudo: false
#
# env:
#   global:
#   - PIP_DEPS="pytest coveralls pytest-cov flake8"
#   - PIP_DEPS="pytest==3.6 coveralls pytest-cov flake8"
#
# python:
# - '3.6'
#
# install:
# - pip install -U tox-travis coverage coveralls
# - travis_retry pip install $PIP_DEPS
# - travis_retry pip install -r requirements.txt
# - travis_retry pip install -e .
# # Has to install miniconda to achive conda installation
# # download and install miniconda
# - wget http://repo.continuum.io/miniconda/Miniconda3-4.1.11-Linux-x86_64.sh -O miniconda.sh;
# - bash miniconda.sh -b -p $HOME/conda
# - export PATH="$HOME/conda/bin:$PATH"
# - hash -r
# - conda config --set always_yes yes --set changeps1 no
# - conda update -q conda
# - conda install -c conda-forge matplotlib
#
#
# script:
# - py.test --pyargs https://github.com/sabiharustam/voltcycle.git --cov-report term-missing --cov=https://github.com/sabiharustam/voltcycle.git
# - py.test --pyargs voltcycle --cov-report term-missing --cov=voltcylce
# #- tox
# - coverage report
#
# after_success:
# - coveralls
#
# after_success:
# - ls -a
# - coveralls`
#

# what language the build will be configured for
language: python

# specify what versions of python will be used
# note that all of the versions listed will be tried
matrix:
    include:
        - python: 3.6
        - python: 3.7

# what branches should be evaluated
branches:
    except:
# Check ALL? Decide as work progresses...

# commands to prepare the conda install - download the latest conda
# and install it and add to path
before_install:
    - wget -O miniconda.sh https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=/home/travis/miniconda3/bin:$PATH
    - conda update --yes conda
    - source $(conda info --root)/etc/profile.d/conda.sh

# list of commands to run to setup the environment
install:
    - conda env create -q -n test-environment python=$TRAVIS_PYTHON_VERSION --file environment.yml
    - conda activate test-environment
    - conda install --yes coverage coveralls flake8

# a list of commands to run before the main script
before_script:
    - flake8 voltcycle

# the actual commands to run
script:
    - coverage run -m unittest discover

# generate a coverage report to send to back to user
after_success:
    - coverage report
    - coveralls
